systers/language-translation

- Gemfile
- Gemfile.lock
- app/admin/articles.rb
- app/admin/categories.rb
- app/admin/dashboard.rb
- app/admin/installations.rb
- app/admin/languages.rb
- app/admin/roles.rb
- app/admin/sites.rb
- app/admin/users.rb
- app/assets/javascripts/active_admin.js.coffee
- app/assets/stylesheets/active_admin.css.scss
- app/controllers/application_controller.rb
- app/models/ability.rb
- app/models/user.rb
- config/initializers/active_admin.rb
- config/routes.rb
- db/migrate/20150713185005_create_active_admin_comments.rb
- db/schema.rb
Issue #10  - ActiveAdmin
1.Installed ActiveAdmin for the application
2.Integrated the current CanCan abilities to grant access to ActiveAdmin
3.Integrated models to display with ActiveAdmin
4.Filled up the dashboard to have a quick look on the application's elements
- You can search, view, edit, delete elements of the application with ease without having to create separate views for each of the elements for the application.
- You can have access to the ActiveAdmin interface under `localhost:3000/admin/` once you're logged in with an admin account.
This pull request closes #10 
---
Screenshots
> Plt#10 active admin

- app/assets/javascripts/application.js
- bower.json
Issue #66  - Underscore.js
1.Added the [Underscore.js](http://underscorejs.org/) library to make JS coding easier.
Run `$ bower install` on your root directory to install the library on your machine.
This pull request closes #66
> 66-add Underscore library

- .travis.yml
Issue #72  - Travis: Migrating from legacy to container-based infrastructure
1.Migrated Travis from legacy to container-based infrastructure.
- Builds now start in less than 10 seconds upon each push.
- Testing is now blazing fast.
http://docs.travis-ci.com/user/migrating-from-legacy/?utm_source=legacy-notice&utm_medium=banner&utm_campaign=legacy-upgrade
This pull request closes #72
> 72-Migrate Travis to container-based infrastructure

- app/assets/javascripts/application.js
- app/assets/javascripts/components/paginator_section.js.jsx
- app/assets/javascripts/plugins/paginator.js.jsx
- app/controllers/users_controller.rb
- app/views/users/index.html.erb
1. Added `paginator.js` library
1. Integrated pagination feature to member list page
> Plt#56 Integration of Kaminari gem + ReactJS

- app/assets/javascripts/application.js
- app/assets/javascripts/components/react-bootstrap.js.jsx.coffee
- app/assets/javascripts/components/sites/show.js.jsx.coffee
- app/assets/javascripts/components/users/index.js.jsx.coffee
- app/assets/javascripts/components/users/show.js.jsx.coffee
- bower.json
Issue #52  - Modals in React
1.Integrated React-Bootstrap (http://react-bootstrap.github.io/) in our application
2.Used their `Modals` for confirming actions.
- Login approvals in `Users Index`
- Granting/Revoking admin rights in `Users Show`
3.Used their `Alerts` to alert a wrong action.
- Wrong username upon adding contributors/volunteers in `Sites Show`
Notice:
- You will have to run `$ bower install`.
- They really do have some nice components that fit in well with React. Take a look and use them yourself: http://react-bootstrap.github.io/components.html
This pull request closes #52
> Plt#52 modal with react bootstrap

- Gemfile
- Gemfile.lock
Issue #77  - Gem Updates
1.Changed the versions of the gems in the Gemfile that had been fixed for no particular reason.
2.Updated gems
3.Checked that there aren't any major updates that required changes in syntaxes
This pull request closes #77
> 77-UpgradeGems

- Capfile
- Gemfile
- Gemfile.lock
- config/deploy.rb
- config/deploy/production.rb
- config/deploy/staging.rb
Here I have added deployment configurations setup; 
1. We have to change server username `[user_name]`
2. This `capistrano` gem is quite old. But it work without any issues. If we need to upgrade, it is possible. 
3. Added `staging` and `production` deployment setup. 
4. I have added AWS fog setting as well.
> 16-setup capistrano so that deploy automatically

- db/seeds.rb
@SaumyaGurtu Removed your email address from the seeds file.
> Clean seeds file by removing real email address

- README.md
I set up the repo locally and the readme setup steps seemed to be missing a few things. Here are my suggested changes.
> Made installation steps clearer

- app/assets/javascripts/application.js
- app/assets/javascripts/errors.coffee
- app/views/shared/_error_messages.html.erb
> PLT#98 | Fix close button for alerts.

- app/models/user.rb
placed a check that only numbers will be accepted in contact
> added number check

- app/views/devise/passwords/new.html.erb
> PLT#108 | Forgot Password. [WIP]

- app/models/user.rb
- db/seeds.rb
- test/factories.rb
* Pull Request fixes issue #113
> User attributes validations are set. Fixes #113

- config/initializers/devise.rb
> Forget Password functioning properly. Fixes #108

- app/models/category.rb
- app/models/country.rb
- app/models/language.rb
- app/models/organization.rb
- app/models/site.rb
- app/models/user.rb
- test/api/articles_controller_test.rb
- test/api/categories_controller_test.rb
- test/api/languages_controller_test.rb
- test/controllers/categories_controller_test.rb
- test/controllers/countries_controller_test.rb
Note: 
1. There can be 2 sites with the same name in different countries.
2. There can be 2 countries with the same name if they are related to the different organizations.
As of now, an admin can create countries and associate it with an organization. We can have the superadmin add the countries (so they are unique across our application) and admin can associate these countries with his/her organization.
> PLT#102 Uniqueness validation for entities' name

- app/controllers/organizations_controller.rb
- app/models/country.rb
- app/models/organization.rb
- db/migrate/20170618074228_update_foregin_key.rb
- db/migrate/20170618074445_update_foregin_key_for_users.rb
- db/migrate/20170618080703_update_foregin_key_for_countries.rb
- db/migrate/20170618081208_update_foregin_key_again_for_countries.rb
- db/schema.rb
> Fixes #101 - Deletes Users on deletion of Organization

- app/assets/stylesheets/custom-web-starter-kit.scss
> Fixes #103 - Text Overflow in Show Pages

- app/uploaders/audio_uploader.rb
- app/uploaders/picture_uploader.rb
- app/views/articles/_form.html.erb
- app/views/articles/show.html.erb
* Added whitelist for audio and image filetypes (for security reasons).
* Cleaned up multiple file upload UI.
* Completes #60.
> Completes #60 - Multiple Audio and Image upload using CarrierWave

- app/models/category.rb
- app/models/country.rb
- app/models/language.rb
- app/models/organization.rb
- app/models/site.rb
- test/api/articles_controller_test.rb
- test/api/categories_controller_test.rb
- test/api/languages_controller_test.rb
- test/controllers/categories_controller_test.rb
- test/controllers/countries_controller_test.rb
- test/controllers/languages_controller_test.rb
- test/controllers/sites_controller_test.rb
* Initial PR by Shubham Patel was failing. Had 12 errors, when tested.
* Errors corrected and hence fixes issue #102
> Fixes #102 - Uniqueness added to necessary parameters. Corresponding Tests Updated

- app/uploaders/picture_uploader.rb
- app/views/articles/_article.html.erb
- app/views/shared/_header.html.erb
* Added thumbnails for articles.
* Updated articles index photos with thumbnails.
* Completes #62
> Completes #62 - Added thumbnails for articles

- app/controllers/application_controller.rb
- app/views/devise/registrations/edit.html.erb
- app/views/welcome/index.html.erb
> Fixes #176 - Remove Avatar not working in Profile Edit page

- app/controllers/articles_controller.rb
- app/models/article.rb
- app/uploaders/picture_uploader.rb
- app/views/articles/_article.html.erb
- app/views/shared/_header.html.erb
- db/migrate/20170620100434_update_foregin_key_for_articles.rb
- db/schema.rb
* Fixes #174 
* Minor UI change to header file for including avatar thumbnail.
> Fixes #174 - Deletion of audio files when article is deleted. Minor UI change for avatar thumbnails

- app/controllers/categories_controller.rb
- test/controllers/categories_controller_test.rb
* Add tests for category search and duplicate category.
* Fixes indentation
> Updates Categories Controller Test

- GSoC2017-PLT-DevelopmentUpdate.md
- README.md
- config/database.yml.example
> Updates developer schematics

- app/controllers/languages_controller.rb
- test/controllers/languages_controller_test.rb
* Add tests for language search and duplicate languages
* Refactors existing controller code
* Fixes indentation
> Updates languages_controller_test

- app/controllers/articles_controller.rb
- test/controllers/articles_controller_test.rb
- test/controllers/contributor/articles_controller_test.rb
* Refactors articles_controller
* Adds tests for create, update and state
* Corrects state error in /test/controllers/contributor/articles_controller_test.rb
> Updates articles_controller_test

- app/controllers/countries_controller.rb
- test/controllers/countries_controller_test.rb
* Add tests for country search and country update
* Refactors countries_controller
> Updates countries_controller_test

- GSoC2017-PLT-DevelopmentUpdate.md
- app/models/article.rb
- test/models/article_test.rb
* Validates presence of phonetic field along with picture and category
* Adds test to verify the same
> Validates phonetic field for photo(article)

- app/controllers/users_controller.rb
- test/controllers/users_controller_test.rb
* Add tests for user index search, create and update
* Refactors users_controller
NOTE:
* approve_user, disapprove_user, grant_admin, revoke_admin functionality not working. Needs to be added to dev task
> Updates users_controller_test

- app/controllers/sites_controller.rb
- app/views/sites/_form.html.erb
- test/controllers/sites_controller_test.rb
* Adds test for sites controller - search, create, edit, destroy
* Refactors sites controller
NOTE:
* add_role, remove_role functionality not working. Needs to be added to dev task
> Updates sites_controller_test

- test/api/articles_controller_test.rb
* Adds article update failure case
NOTE:
* Unable to find situation where destroy will fail for articles, languages and categories API, hence that else clause not covered.
> Updates articles_controller_api_test

- Gemfile
- Gemfile.lock
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- test/integration/user_action_test.rb
- test/integration/user_routing_test.rb
- test/test_helper.rb
* Adds capybara gem to facilitate integration testing
* Adds user_action_test.rb to test user actions on the whole like signing up, logging in and updating user details from the front end perspective
* Renames user_flow_test.rb to a more appropriate name -> user_routing_test.rb
* Updates user related (devise) partials with necessary 'id' values for the form fields
> Adds integration testing for user actions

- backup/README.md
- backup/backup_setup.sh
- backup/crontab_setup.sh
- backup/schedule.rb.example
- backup/systers_plt_db_backup.rb.example
* Adds necessary commands which needs to be executed for setting up a backup server.
* Supports multiple secondary servers and smtp based mail notifications in case of failure.
> Adds backup script

- test/api/articles_controller_test.rb
* Adds test to check presence of other params
* Update Failure for picture fails, gives 200 instead of 422
> Updates api/articles_controller_test

- Gemfile
- Gemfile.lock
- SECURITY_DETAILS.html
- SECURITY_DETAILS.md
* Adds brakeman security gem for security testing
Key points from the report :
* Upgrade Rails from 4.2.1 to 4.2.7.1 to prevent Cross Site Scripting, SQL Injection, Denial of Service (PRIORITY : HIGH)
* Upgrade rails-html-sanitizer 1.0.2 to 1.0.3 to prevent Cross Site Scripting (PRIORITY : MEDIUM)
> Adds brakeman gem and security report

- GSoC2017-PLT-DevelopmentUpdate.md
- app/admin/dashboard.rb
* article.english being blank (which is perfectly valid according to the model) was creating an issue
* Updates the development status file
* This pull request closes #202 
> Issue #202 - Fixes Unable to view Admin Dashboard

- app/admin/users.rb
* Adds condition to prevent admin from changing volunteers username. Fixes #211.
* Also adds login_approval_at field. Implements #212 for admin panel.
NOTE: 2 issues in one PR , as #212 requires #211
> Fixes Issue #211 and #212

- app/controllers/sites_controller.rb
- db/schema.rb
- db/seeds.rb
- test/controllers/sites_controller_test.rb
* Deletes all the volunteers and contributors belonging to a site, when a site is deleted.
* Fixes Issue #210.
* Updates Testing Suite for the same.
> Fixes Issue #210 - Volunteer and Contributor Deletion on Site Delete

- app/views/countries/show.html.erb
* Adds Email address hyperlink for contact information.
* Adds count of the number of sites in the given country's show page.
> Fixes #209 - Adds ContactInfo and SiteCount

- app/controllers/sites_controller.rb
- app/views/sites/show.html.erb
- config/routes.rb
- test/controllers/sites_controller_test.rb
* Implements create volunteer (linked with add_role)
* Implements volunteer delete from site page
* Implements remove volunteer role (linked with remove_role)
* Displays all volunteers in a give site
* Similarly for contributors
NOTE: 3 Issues in one PR, as they are all linked
* Updates testing suite with relevant tests for add_role and remove_role in sites_controller
* Updates sites_controller correspondingly
> Fixes #207, #208 and #215 - Volunteer/Contributor for Site

- app/controllers/users_controller.rb
- app/views/users/index.html.erb
- test/controllers/users_controller_test.rb
* Implements User Approval/Disapproval and Admin Grant/Revoke
* Completes #214
> Fixes #214 - UserApproval, Admin Grant/Revoke Implementation

- GSoC2017-PLT-DevelopmentUpdate.md
* Updates Development Status checklist file with completed tasks.
* Pending Tasks are :
- UI Improvements
- Making the application work offline
- Automatic syncing of data from cloud, when the application is connected to the web.
NOTE : Please merge this PR once #223 and #224 is reviewed and merged.
> Updates PLT Development Checklist

- app/controllers/articles_controller.rb
- app/models/article.rb
- app/models/audio.rb
- app/uploaders/audio_uploader.rb
- app/views/articles/_form.html.erb
- test/models/audio_test.rb
* Audio Uploader had been partially broken, due to insufficient attribute permissions
* Adds necessary audio_attributes and validations
> Fixes Broken Audio Uploader

- app/views/sites/show.html.erb
- test/controllers/sites_controller_test.rb
* Modifies sites show page to accommodate the same
* Updates test to account in another similar condition regarding non existent user
> Should'nt show add/remove role form for volunteer

- app/views/languages/index.html.erb
* Modified permissions for viewing articles of each language, language tab
> Makes articles in language visible for volunteers

- README.md
* Adds details on where to refer to for backup
* Adds imagemagick as a dependency to be installed
> Updates README with backup and imagemagick

- app/views/users/index.html.erb
Resolves https://github.com/systers/language-translation/issues/237
> Corrected the spelling for approve

- app/assets/stylesheets/application.css
- app/views/devise/registrations/edit.html.erb
Since flex boxes work best on div tags, I converted the span tags to div tags. Also, necessary css code has been added. This resolves the overflow problem generated in certain screen sizes.
> Issue #232 : Fixed API key overflow problem

- CONTRIBUTING.md
Include a summary of the change and relevant motivation/context. List any dependencies that are required for this change.
Fixes # [ISSUE]
**Delete irrelevant options.**
- Code
- Quality Assurance
- User Interface
- Outreach
- Documentation
**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- This change requires a documentation update (software upgrade on readme file)
- New feature (non-breaking change which adds functionality pre-approved by mentors)
Describe the tests you ran to verify your changes. Provide instructions or GIFs so we can reproduce. List any relevant details for your test.
**Delete irrelevant options.**
**Code/Quality Assurance Only**
> Janiceilene patch 2
